### ISSUE TITLE
Syntax highlighting broken in yaml

### ISSUE THREAD

**Issue by andoneve** [nanoparsec/twilightsparkle-syntax#1]
I love this syntax theme and want to keep using it, but it's not integrating well with yaml and Dockerfiles

In a yaml file, keys and values have the same syntax highlighting and makes it difficult to read. Same with Dockerfiles.

For example, these keys and values have the same color (green):

config.yml

```
version: 2.0
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ''
    parallelism: 5
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - app-bundle-{{ checksum "Gemfile.lock" }}
            - app-bundle
```
